/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compubicuasmartcity;

/**
 *
 * @author Jose
 */
public class FrameControl extends javax.swing.JFrame {

    /**
     * Creates new form FrameControl
     */
    public FrameControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        linea1Panel = new javax.swing.JPanel();
        linea1Marquesina1Field = new javax.swing.JTextField();
        linea1Marquesina2Field = new javax.swing.JTextField();
        linea1Marquesina3Field = new javax.swing.JTextField();
        linea1Marquesina4Field = new javax.swing.JTextField();
        linea1Marquesina0Field = new javax.swing.JTextField();
        linea1Marquesina0Label = new javax.swing.JLabel();
        linea1Marquesina1Label = new javax.swing.JLabel();
        linea1Marquesina3Label = new javax.swing.JLabel();
        linea1Marquesina2Label = new javax.swing.JLabel();
        linea1Marquesina4Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centro de control");
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setText("CENTRO DE CONTROL");

        jLabel2.setText("Linea 2");

        jLabel3.setText("Linea 1");

        linea1Panel.setBorder(new javax.swing.border.MatteBorder(null));

        linea1Marquesina1Field.setEditable(false);
        linea1Marquesina1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina1Field.setText("0");
        linea1Marquesina1Field.setPreferredSize(new java.awt.Dimension(20, 20));
        linea1Marquesina1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina1FieldActionPerformed(evt);
            }
        });

        linea1Marquesina2Field.setEditable(false);
        linea1Marquesina2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina2Field.setText("0");
        linea1Marquesina2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina2FieldActionPerformed(evt);
            }
        });

        linea1Marquesina3Field.setEditable(false);
        linea1Marquesina3Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina3Field.setText("0");
        linea1Marquesina3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina3FieldActionPerformed(evt);
            }
        });

        linea1Marquesina4Field.setEditable(false);
        linea1Marquesina4Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina4Field.setText("0");
        linea1Marquesina4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina4FieldActionPerformed(evt);
            }
        });

        linea1Marquesina0Field.setEditable(false);
        linea1Marquesina0Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina0Field.setText("0");
        linea1Marquesina0Field.setPreferredSize(new java.awt.Dimension(20, 20));
        linea1Marquesina0Field.setRequestFocusEnabled(false);
        linea1Marquesina0Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina0FieldActionPerformed(evt);
            }
        });

        linea1Marquesina0Label.setText("Marquesina 0:");

        linea1Marquesina1Label.setText("Marquesina 1:");

        linea1Marquesina3Label.setText("Marquesina 3:");

        linea1Marquesina2Label.setText("Marquesina 2:");

        linea1Marquesina4Label.setText("Marquesina 4:");

        jLabel4.setText("viajeros");

        jLabel5.setText("viajeros");

        jLabel6.setText("viajeros");

        jLabel7.setText("viajeros");

        jLabel8.setText("viajeros");

        javax.swing.GroupLayout linea1PanelLayout = new javax.swing.GroupLayout(linea1Panel);
        linea1Panel.setLayout(linea1PanelLayout);
        linea1PanelLayout.setHorizontalGroup(
            linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linea1PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(linea1Marquesina1Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(linea1Marquesina2Field))
                    .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(linea1PanelLayout.createSequentialGroup()
                            .addComponent(linea1Marquesina3Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(linea1Marquesina3Field))
                        .addGroup(linea1PanelLayout.createSequentialGroup()
                            .addComponent(linea1Marquesina4Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(linea1Marquesina4Field))
                        .addGroup(linea1PanelLayout.createSequentialGroup()
                            .addComponent(linea1Marquesina0Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(linea1Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        linea1PanelLayout.setVerticalGroup(
            linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linea1PanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linea1Marquesina0Label)
                            .addComponent(linea1Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linea1Marquesina1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linea1Marquesina1Label)
                            .addComponent(jLabel5))
                        .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(linea1PanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(linea1Marquesina2Label))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linea1PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))))
                    .addComponent(linea1Marquesina2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linea1Marquesina3Label)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linea1Marquesina4Label)
                    .addComponent(jLabel7))
                .addGap(77, 77, 77))
        );

        jLabel9.setText("Marquesina 0:");

        jLabel10.setText("Marquesina 1:");

        jLabel11.setText("Marquesina 2:");

        jLabel12.setText("Marquesina 3:");

        jLabel13.setText("Marquesina 4:");

        jLabel14.setText("viajeros");

        jLabel15.setText("viajeros");

        jLabel16.setText("viajeros");

        jLabel17.setText("viajeros");

        jLabel18.setText("viajeros");

        jTextField1.setText("0");

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addComponent(linea1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel3)
                    .addContainerGap(645, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linea1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel3)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linea1Marquesina0FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina0FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina0FieldActionPerformed

    private void linea1Marquesina1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina1FieldActionPerformed

    private void linea1Marquesina2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina2FieldActionPerformed

    private void linea1Marquesina3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina3FieldActionPerformed

    private void linea1Marquesina4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina4FieldActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField linea1Marquesina0Field;
    private javax.swing.JLabel linea1Marquesina0Label;
    public javax.swing.JTextField linea1Marquesina1Field;
    private javax.swing.JLabel linea1Marquesina1Label;
    public javax.swing.JTextField linea1Marquesina2Field;
    private javax.swing.JLabel linea1Marquesina2Label;
    public javax.swing.JTextField linea1Marquesina3Field;
    private javax.swing.JLabel linea1Marquesina3Label;
    public javax.swing.JTextField linea1Marquesina4Field;
    private javax.swing.JLabel linea1Marquesina4Label;
    private javax.swing.JPanel linea1Panel;
    // End of variables declaration//GEN-END:variables
}
