/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compubicuasmartcity;

/**
 *
 * @author Jose
 */
public class FrameControl extends javax.swing.JFrame {

    /**
     * Creates new form FrameControl
     */
    public FrameControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        linea1Panel = new javax.swing.JPanel();
        linea1Marquesina1Field = new javax.swing.JTextField();
        linea1Marquesina2Field = new javax.swing.JTextField();
        linea1Marquesina3Field = new javax.swing.JTextField();
        linea1Marquesina4Field = new javax.swing.JTextField();
        linea1Marquesina0Field = new javax.swing.JTextField();
        linea1Marquesina0Label = new javax.swing.JLabel();
        linea1Marquesina1Label = new javax.swing.JLabel();
        linea1Marquesina3Label = new javax.swing.JLabel();
        linea1Marquesina2Label = new javax.swing.JLabel();
        linea1Marquesina4Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        linea2Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        linea2Marquesina0Field = new javax.swing.JTextField();
        linea2Marquesina1Field = new javax.swing.JTextField();
        linea2Marquesina2Field = new javax.swing.JTextField();
        linea2Marquesina3Field = new javax.swing.JTextField();
        linea2Marquesina4Field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        linea1BusStatus = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        autobus2ViajerosField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centro de control");

        jLabel1.setText("CENTRO DE CONTROL");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setText("Linea 1");

        linea1Panel.setBorder(new javax.swing.border.MatteBorder(null));

        linea1Marquesina1Field.setEditable(false);
        linea1Marquesina1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina1Field.setText("0");
        linea1Marquesina1Field.setPreferredSize(new java.awt.Dimension(20, 20));
        linea1Marquesina1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina1FieldActionPerformed(evt);
            }
        });

        linea1Marquesina2Field.setEditable(false);
        linea1Marquesina2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina2Field.setText("0");
        linea1Marquesina2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina2FieldActionPerformed(evt);
            }
        });

        linea1Marquesina3Field.setEditable(false);
        linea1Marquesina3Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina3Field.setText("0");
        linea1Marquesina3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina3FieldActionPerformed(evt);
            }
        });

        linea1Marquesina4Field.setEditable(false);
        linea1Marquesina4Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina4Field.setText("0");
        linea1Marquesina4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina4FieldActionPerformed(evt);
            }
        });

        linea1Marquesina0Field.setEditable(false);
        linea1Marquesina0Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea1Marquesina0Field.setText("0");
        linea1Marquesina0Field.setPreferredSize(new java.awt.Dimension(20, 20));
        linea1Marquesina0Field.setRequestFocusEnabled(false);
        linea1Marquesina0Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea1Marquesina0FieldActionPerformed(evt);
            }
        });

        linea1Marquesina0Label.setText("Marquesina 0:");

        linea1Marquesina1Label.setText("Marquesina 1:");

        linea1Marquesina3Label.setText("Marquesina 3:");

        linea1Marquesina2Label.setText("Marquesina 2:");

        linea1Marquesina4Label.setText("Marquesina 4:");

        jLabel4.setText("viajeros");

        jLabel5.setText("viajeros");

        jLabel6.setText("viajeros");

        jLabel7.setText("viajeros");

        jLabel8.setText("viajeros");

        javax.swing.GroupLayout linea1PanelLayout = new javax.swing.GroupLayout(linea1Panel);
        linea1Panel.setLayout(linea1PanelLayout);
        linea1PanelLayout.setHorizontalGroup(
            linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linea1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea1Marquesina4Field))
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea1Marquesina3Field))
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea1Marquesina2Field))
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea1Marquesina1Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(linea1PanelLayout.createSequentialGroup()
                        .addComponent(linea1Marquesina0Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea1Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        linea1PanelLayout.setVerticalGroup(
            linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linea1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina0Label)
                    .addComponent(linea1Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina1Label)
                    .addComponent(linea1Marquesina1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina2Label)
                    .addComponent(linea1Marquesina2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina3Label)
                    .addComponent(linea1Marquesina3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linea1Marquesina4Label)
                    .addComponent(linea1Marquesina4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Linea 2");

        linea2Panel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel9.setText("Marquesina 0:");

        jLabel10.setText("Marquesina 1:");

        jLabel11.setText("Marquesina 2:");

        jLabel12.setText("Marquesina 3:");

        jLabel13.setText("Marquesina 4:");

        jLabel14.setText("viajeros");

        jLabel15.setText("viajeros");

        jLabel16.setText("viajeros");

        jLabel17.setText("viajeros");

        jLabel18.setText("viajeros");

        linea2Marquesina0Field.setEditable(false);
        linea2Marquesina0Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea2Marquesina0Field.setText("0");

        linea2Marquesina1Field.setEditable(false);
        linea2Marquesina1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea2Marquesina1Field.setText("0");
        linea2Marquesina1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea2Marquesina1FieldActionPerformed(evt);
            }
        });

        linea2Marquesina2Field.setEditable(false);
        linea2Marquesina2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea2Marquesina2Field.setText("0");
        linea2Marquesina2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea2Marquesina2FieldActionPerformed(evt);
            }
        });

        linea2Marquesina3Field.setEditable(false);
        linea2Marquesina3Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea2Marquesina3Field.setText("0");
        linea2Marquesina3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea2Marquesina3FieldActionPerformed(evt);
            }
        });

        linea2Marquesina4Field.setEditable(false);
        linea2Marquesina4Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        linea2Marquesina4Field.setText("0");
        linea2Marquesina4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linea2Marquesina4FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linea2PanelLayout = new javax.swing.GroupLayout(linea2Panel);
        linea2Panel.setLayout(linea2PanelLayout);
        linea2PanelLayout.setHorizontalGroup(
            linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linea2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linea2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea2Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(linea2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea2Marquesina1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(linea2PanelLayout.createSequentialGroup()
                        .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, linea2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linea2Marquesina3Field))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, linea2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linea2Marquesina2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)))
                    .addGroup(linea2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea2Marquesina4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        linea2PanelLayout.setVerticalGroup(
            linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linea2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(linea2Marquesina0Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(linea2Marquesina1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(linea2Marquesina2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(linea2Marquesina3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linea2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(linea2Marquesina4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linea1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linea2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(linea2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linea1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("Autobuses linea 1");

        linea1BusStatus.setColumns(20);
        linea1BusStatus.setRows(5);
        jScrollPane1.setViewportView(linea1BusStatus);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel19)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Estado autobús 2");

        jLabel22.setText("Viajeros: ");

        jLabel24.setText("Posicion:");

        autobus2ViajerosField.setEditable(false);
        autobus2ViajerosField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        autobus2ViajerosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autobus2ViajerosFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autobus2ViajerosField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(autobus2ViajerosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linea1Marquesina0FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina0FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina0FieldActionPerformed

    private void linea1Marquesina1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina1FieldActionPerformed

    private void linea1Marquesina2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina2FieldActionPerformed

    private void linea1Marquesina3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina3FieldActionPerformed

    private void linea1Marquesina4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea1Marquesina4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea1Marquesina4FieldActionPerformed

    private void linea2Marquesina1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea2Marquesina1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea2Marquesina1FieldActionPerformed

    private void linea2Marquesina2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea2Marquesina2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea2Marquesina2FieldActionPerformed

    private void linea2Marquesina3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea2Marquesina3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea2Marquesina3FieldActionPerformed

    private void linea2Marquesina4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linea2Marquesina4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linea2Marquesina4FieldActionPerformed

    private void autobus2ViajerosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autobus2ViajerosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autobus2ViajerosFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField autobus2ViajerosField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea linea1BusStatus;
    public javax.swing.JTextField linea1Marquesina0Field;
    private javax.swing.JLabel linea1Marquesina0Label;
    public javax.swing.JTextField linea1Marquesina1Field;
    private javax.swing.JLabel linea1Marquesina1Label;
    public javax.swing.JTextField linea1Marquesina2Field;
    private javax.swing.JLabel linea1Marquesina2Label;
    public javax.swing.JTextField linea1Marquesina3Field;
    private javax.swing.JLabel linea1Marquesina3Label;
    public javax.swing.JTextField linea1Marquesina4Field;
    private javax.swing.JLabel linea1Marquesina4Label;
    private javax.swing.JPanel linea1Panel;
    public javax.swing.JTextField linea2Marquesina0Field;
    public javax.swing.JTextField linea2Marquesina1Field;
    public javax.swing.JTextField linea2Marquesina2Field;
    public javax.swing.JTextField linea2Marquesina3Field;
    public javax.swing.JTextField linea2Marquesina4Field;
    private javax.swing.JPanel linea2Panel;
    // End of variables declaration//GEN-END:variables
}
